### PR TITLE
Use go modules, enable GitHub Actions

### PR DESCRIPTION
**Pull request by ustiugov**

### CODE REVIEW

**Comment by ustiugov** [comment]
@amariucaitheodor could you please review the CI code and other changes?

**Comment by amariucaitheodor** [comment]
There are 10 unresolved error annotations, other than that looks good to me.

**Comment by ustiugov** [comment]
yeah, I know that there are linter errors. this code is 3 years old
thanks!

**Comment by boramalper** [comment]
@ustiugov Ready for review.

**Review by ustiugov — COMMENTED** [review]
lgtm, please merge

**Pull request merged**
